version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=crm_db
      - JWT_SECRET=your-secret-key-here
      - SERVER_PORT=443
    depends_on:
      - postgres
    networks:
      - crm-network
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network
    restart: always

volumes:
  postgres_data:

networks:
  crm-network:
    driver: bridge 